car_rent/car_rent/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('captcha/', include('captcha.urls')),
    path('', include('cars.urls', namespace='cars')),
    path('', include('users.urls', namespace='users')),


]
if settings.DEBUG:
    urlpatterns = [
                      # ...
                      path("__debug__/", include("debug_toolbar.urls")),
                  ] + urlpatterns
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

car_rent/cars/urls.py
from django.urls import path
from .views import *
from django.views.decorators.cache import cache_page

app_name = 'cars'
urlpatterns = [
    path('', index, name='home'),
    path('car-posts', CarView.as_view(), name='cars'),
    path('car-details/<slug:car_slug>/', CarDetails.as_view(), name='car_details'),
    path('about/', about, name='about'),
    path('contact/', ContactFormView.as_view(), name='contact'),
    path('map/', MapView.as_view(), name='map'),
    path('add-car/', AddCarView.as_view(), name='add_car'),
    path('success/', successful_post, name='success')

]
# path('', cache_page(80)(HomeView.as_view()), name='home'),
# path('about/', cache_page(80)(about), name='about'),

car_rent/users/urls.py
from django.urls import path
from .views import *
from django.views.decorators.cache import cache_page

app_name = 'users'
urlpatterns = [

    path('register/', SignUp.as_view(), name='register'),
    path('login/', LoginUser.as_view(), name='login'),
    path('logout/', logout_user, name='logout'),
    path('user_profile/<slug:user_slug>/', ShowUser.as_view(), name='user_profile'),
    path('update_profile/', UpdateProfileView.as_view(), name='update_profile'),

]

car_rent/cars/models.py
from django.db import models
import datetime
from django.urls import reverse
from users.models import UserProfile




def user_car_upload_to(instance, filename):
    car_slug = instance.slug
    current_time = datetime.datetime.now()
    filename = f'{current_time}_{filename}'
    return f'cars/{car_slug}/{filename}'


class CarCategory(models.Model):
    name = models.CharField(max_length=255,
                            choices=[('economy', 'Economy'), ('standard', 'Standard'), ('luxury', 'Luxury')],
                            default='economy')

    def __str__(self):
        return self.name

    class Meta:
        verbose_name_plural = 'Car categories'


class CarPost(models.Model):
    title = models.CharField(max_length=255)
    slug = models.SlugField(unique=True, verbose_name='URL', db_index=True, max_length=255)

    status = models.CharField(max_length=20, choices=[('available', 'Available'), ('rented', 'Rented'),
                                                      ('under_repair', 'Under Repair')], default='available')
    daily_rent_cost = models.DecimalField(max_digits=10, decimal_places=2)
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='time of creation')
    updated_at = models.DateTimeField(auto_now=True, verbose_name='time of update')
    category = models.ForeignKey(CarCategory, on_delete=models.CASCADE)
    user = models.ForeignKey(UserProfile, on_delete=models.CASCADE)
    model = models.CharField(max_length=255)
    vendor = models.CharField(max_length=255)
    year = models.IntegerField()
    photo = models.ImageField(upload_to=user_car_upload_to, null=True, blank=True)
    description = models.TextField(blank=False)
    is_published = models.BooleanField(default=True)

    def __str__(self):
        return self.slug

    class Meta:
        verbose_name = 'Post about car'
        verbose_name_plural = 'Posts about cars'
        ordering = ['-created_at', 'title']


class RentalDeal(models.Model):
    car = models.ForeignKey(CarPost, on_delete=models.CASCADE)
    client = models.ForeignKey(UserProfile, on_delete=models.CASCADE)
    start_date = models.DateField()
    end_date = models.DateField()
    total_cost = models.DecimalField(max_digits=10, decimal_places=2)
    status = models.CharField(max_length=20, choices=[('active', 'Active'), ('completed', 'Completed')],
                              default='active')

    def __str__(self):
        return f"Deal ID: {self.pk} - {self.car} ({self.start_date} to {self.end_date})"


class Search(models.Model):
    name = models.CharField(max_length=60, verbose_name='Branch name')
    lng = models.FloatField(verbose_name='Longitude')
    lat = models.FloatField(verbose_name='Latitude')
    date = models.DateTimeField(auto_now_add=True)
    active = models.BooleanField(default=True, verbose_name='Status')

    def __str__(self):
        return self.name

car_rent/cars/forms.py
from django import forms
from captcha.fields import CaptchaField
from .models import CarPost


class ContactForm(forms.Form):
    name = forms.CharField(label='Name', max_length=255)
    email = forms.EmailField(label='Email', max_length=255)
    content = forms.CharField(label='Complaint', widget=forms.Textarea(attrs={'cols': 60, 'rows': 10}))
    captcha = CaptchaField()


class CarPostForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):

        super().__init__(*args, **kwargs)

        self.fields['category'].empty_label = "Category not selected"

    class Meta:
        model = CarPost
        fields = ['title', 'description', 'status', 'daily_rent_cost', 'photo',
                  'category', 'model', 'vendor', 'year']

car_rent/cars/views.py
import random

import folium
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import ListView, FormView, CreateView, DetailView
from .models import CarPost, Search, UserProfile
from .forms import ContactForm, CarPostForm
from django.shortcuts import redirect, render
from django.urls import reverse_lazy
from django.views import View
from .utils import DataMixin


class AddCarView(LoginRequiredMixin, DataMixin, CreateView):
    form_class = CarPostForm
    template_name = 'cars/add_car.html'
    login_url = reverse_lazy('cars:home')  # redirect if user is not authorized
    raise_exception = True  # access is forbidden
    success_url = reverse_lazy('cars:success')

    def form_valid(self, form):
        user_profile = UserProfile.objects.get(user=self.request.user)
        slug = f"{user_profile}{random.randrange(100)}"
        form.instance.user = user_profile
        form.instance.slug = slug
        return super().form_valid(form)

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        c_def = self.get_user_context(title="Add Car")

        return {**context, **c_def}


class CarView(DataMixin, ListView):
    template_name = 'cars/cars.html'
    model = CarPost

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)

        title = self.get_user_context(title="Cars")

        return {**context, **title}


class CarDetails(DataMixin, DetailView):
    model = CarPost
    template_name = 'cars/car_detail.html'
    slug_url_kwarg = 'car_slug'
    context_object_name = 'car'

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        title = self.get_user_context(title='Car details')

        return {**context, **title}


class ContactFormView(DataMixin, FormView, View):
    template_name = 'cars/contact.html'
    form_class = ContactForm
    success_url = reverse_lazy('cars:home')

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        title = self.get_user_context(title='Contact')
        return {**context, **title}

    def form_valid(self, form):
        return redirect('cars:home')


class MapView(ListView):
    template_name = 'cars/map.html'
    model = Search

    def get_context_data(self, *, object_list=None, **kwargs):
        title = 'Map'
        form = folium.Figure(height=1000, width=1100)
        m = folium.Map(location=[-0.43, 0.32], tiles="openstreetmap", zoom_start=2.2, min_zoom=2,
                       max_bounds=True).add_to(form)
        for branch in self.model.objects.filter(active=True):
            folium.Marker([branch.lng, branch.lat], tooltip='Click for more', popup="Branch").add_to(m)

        # Get HTML Representation of Map Object
        map_html = m._repr_html_()

        context = {
            'title': title,  # Corrected title assignment
            'map': map_html
        }
        return context

    def get_queryset(self):
        pass


def index(request):
    context = {
        'title': 'Home page'
    }
    return render(request, 'cars/index.html', context=context)


def about(request):
    context = {
        'title': 'About us'
    }
    return render(request, 'cars/about.html', context=context)


def successful_post(request):
    context = {
        'title': 'Success',
        'message': 'The post has been published'
    }
    return render(request, 'cars/success.html', context=context)

car_rent/cars/templates/cars/about.html
{%extends 'cars/base.html'%}

{%block content%}
<!-- Main Content Goes Here -->
<div class="container mt-4">
    <h1>About us</h1>
</div>

{%endblock%}

car_rent/cars/templates/cars/add_car.html
{%extends 'cars/base.html'%}


{%block content%}
<!-- Main Content Goes Here -->
<div class="container mt-4">
    <h1>Welcome to Car Rent home page</h1>
    <div class="card">
        <div class="card-header"><b>Login</b></div>
        <div class="card-body">
            <form method="post">
                {% csrf_token %}

                {%for f in form%}
                <p><label class="form-label" for="{{ f.id_for_label }}">{{f.label}}: </label>{{ f }}</p>
                {%if f.errors%}
                <div class="error-block">{{ f.errors }}</div>
                {%endif%}
                {%endfor%}
                {%if form.non_field_errors%}
                <div class="error-block">{{form.non_field_errors}}</div>
                {%endif%}
                <button class="button-80" role="button" type="submit">Add Car</button>
                <h1>{{profile}}</h1>
            </form>
            <p class="mt-3">Do not have an account? <a href="{% url 'users:register' %}">Create an account</a></p>
        </div>
    </div>

</div>

{%endblock%}

car_rent/cars/templates/cars/base.html
{%load static%}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{{ title }}</title>

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">

    <!-- Google Fonts -->
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@400;700&display=swap" rel="stylesheet">

    <!-- Font Awesome -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.3.0/css/all.min.css">
    <!-- Custom styles -->
    <link rel="stylesheet" href="{% static 'cars/css/styles.css' %}">


    {%block custom_styles%}

    {%endblock%}

</head>

<body>

<!-- Navbar -->
<nav class="navbar navbar-expand-lg navbar-dark navbar-custom">
    <a class="navbar-brand" href="#">Car Rent</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav"
            aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav ml-auto">
            <li class="nav-item active">
                <a class="nav-link" href="{% url 'cars:home' %}"><i class="fas fa-home"></i> Home</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'cars:cars' %}"><i class="fas fa-car"></i> Cars</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'cars:about' %}"><i class="fas fa-info-circle"></i> About Us</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'cars:contact' %}"><i class="fas fa-envelope"></i> Contact</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'cars:map' %}"><i class="fa fa-map-signs"></i> Our
                    branches</a>
            </li>
            {% if request.user.is_authenticated%}

            <li class="nav-item">
                <a class="nav-link" href="{% url 'users:user_profile' user_slug=request.user.userprofile.slug %}"><i
                        class="fas fa-user"></i> Profile</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'users:logout' %}"><i class="fas fa-sign-out-alt"></i> Log Out</a>
            </li>
            {%else%}
            <li class="nav-item">
                <a class="nav-link" href="{% url 'users:register' %}"><i class="fas fa-user-plus"></i> Register</a>
            </li>
            {%endif%}

        </ul>
    </div>
</nav>
{%block content%}


{%endblock%}
<!-- Footer -->
<footer class="footer-custom">
    <div class="container">
        <p>&copy; 2023 Car Rent</p>
        <p>Batys-2, Aktobe, Kazakhstan</p>
        <p><i class="fas fa-phone"></i>+7 775 054 23 76</p>
    </div>
</footer>

<!-- Bootstrap Scripts -->
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.3/dist/umd/popper.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>

<!-- Font Awesome Scripts -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.3.0/js/all.min.js"></script>

</body>

</html>

car_rent/cars/templates/cars/car_detail.html
{%extends 'cars/base.html'%}
{%load static%}
{%block custom_styles%}
<link rel="stylesheet" href=
        "https://unpkg.com/purecss@1.0.1/build/pure-min.css">

<style>
        /* Custom styles */
        .blog {
            margin: 0 auto;
            max-width: 800px;
        }

        .blog-header {
            text-align: center;
            padding: 20px;
        }

        .blog-title {
            font-size: 36px;
            font-weight: bold;
        }

        .blog-subtitle {
            font-size: 24px;
            color: gray;
        }

        .blog-post {
            margin-bottom: 20px;
            padding: 20px;
            border: 1px solid lightgray;
        }

        .blog-post-title {
            font-size: 28px;
            margin-bottom: 10px;
        }

        .blog-post-date {
            font-size: 18px;
            color: gray;
            margin-bottom: 20px;
        }

        .blog-post-content {
            font-size: 18px;
            line-height: 1.5;
        }



</style>
{%endblock%}
{%block content%}
<!-- Main Content Goes Here -->
<div class="container my-5">
    <div class="row">
        <div class="col-lg-6">
            <h1>{{ car.title }}</h1>
            <p><strong>Slug:</strong> {{ car.slug }}</p>
            <p><strong>Description:</strong> {{ car.description }}</p>
            <p><strong>Status:</strong> {{ car.status }}</p>
            <p><strong>Daily Rent Cost:</strong> {{ car.daily_rent_cost }} USD</p>
            <p><strong>Created At:</strong> {{ car.created_at }}</p>
            <p><strong>Updated At:</strong> {{ car.updated_at }}</p>
            <p><strong>Is Published:</strong> {% if car.is_published %}Yes{% else %}No{% endif %}</p>
            <p><strong>Car Model:</strong> {{ car.model }}</p>
            <!-- Add more attributes as needed -->
        </div>
        <div class="col-lg-6">
            <img src="{{ car.photo.url }}">
        </div>
    </div>
</div>


{%endblock%}

car_rent/cars/templates/cars/cars.html
{%extends 'cars/base.html'%}
{%load static%}
{%block custom_styles%}
<link rel="stylesheet" href="{% static 'cars/css/card.css' %}">
{%endblock%}

{%block content%}
<!-- Main Content Goes Here -->
<div class="container mt-4">
    <h1>Welcome to Car Rent home page</h1>
    <a class="button-80" href="{% url 'cars:add_car' %}">Add Car</a>
    <h1>Available cars</h1>
</div>

<main>

    <div class="container-fluid bg-trasparent my-4 p-3" style="position: relative;">
        <div class="row row-cols-1 row-cols-xs-2 row-cols-sm-2 row-cols-lg-4 g-3">
            {% for car in cars %}
            <div class="col">
                <div class="card h-100 shadow-sm">
                    {%if car.photo%}
                    <img src="{{ car.photo.url }}"
                         class="card-img-top" alt="car_photo">
                    {%endif%}
                    <div class="card-body">
                        <div class="clearfix mb-3">
                            <span class="float-start badge rounded-pill bg-primary">{{ car.model }}</span>
                            <span class="float-end price-hp">  ㅤㅤㅤ</span>
                            <span class="float-end price-hp">Rent Price: {{car.daily_rent_cost}}$</span>
                        </div>
                        <h5 class="card-title">Description: {{ car.description }}</h5>
                        <h5 class="card-title">Owner: {{ car.user.first_name }}</h5>
                        <div class="text-center my-4">
                            <a href="{% url 'cars:car_details' car_slug=car.slug %}" class="btn btn-warning">Check
                                offer</a>
                        </div>
                    </div>
                </div>
            </div>
            {%endfor%}
            <!-- Similar structure for the other three cards -->
        </div>
    </div>
</main>


{%endblock%}

car_rent/cars/templates/cars/contact.html
{%extends 'cars/base.html'%}

{%block content%}
<!-- Main Content Goes Here -->
<div class="container mt-5">
    <div class="row justify-content-center">
        <div class="col-md-6">
            <div class="card">
                <div class="card-header"><b>Registration</b></div>
                <div class="card-body">
                    <form method="post">
                        {% csrf_token %}
                        {% for f in form %}
                        <p><label class="form-label" for="{{ f.id_for_label }}">{{f.label}}: </label>{{ f }}</p>
                        {%if f.errors%}
                        <div class="error-block">{{ f.errors }}</div>
                        {%endif%}
                        {% endfor %}

                        <button class="button-80" role="button" type="submit">Send a complaint</button>

                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

{%endblock%}

car_rent/cars/templates/cars/index.html
{%extends 'cars/base.html'%}

{%block content%}
<!-- Main Content Goes Here -->
<div class="container mt-4">
    <h1>Home page</h1>
</div>

{%endblock%}

car_rent/cars/templates/cars/map.html
{%extends 'cars/base.html'%}

{%block content%}
<!-- Main Content Goes Here -->
<div class="container-fluid">
    <div class="row">
        <!-- Sidebar -->

        <nav id="sidebar" class="col-md-3 col-lg-2 d-md-block bg-light sidebar">
            <br>
            <div class="position-sticky">
                <div class="my-4">
                    <h4>Search</h4>
                    <div class="input-group">
                        <form method="POST">
                            {% csrf_token %}
                            <input type="text" class="form-control" placeholder="Search...">
                            <div class="input-group-append">
                                <button class="btn btn-outline-secondary" type="submit">Go</button>
                            </div>
                        </form>
                    </div>
                </div>

            </div>
        </nav>

        <!-- Content -->
        <main class="col-md-9 ms-sm-auto col-lg-10 px-md-4">
            <div class="row justify-content-center">
                <div class="col-md-8 mx-auto">
                    <div>
                        {{ map|safe }}
                    </div>
                </div>
            </div>
        </main>
    </div>
</div>
{%endblock%}

car_rent/cars/templates/cars/success.html
{% extends 'cars/base.html' %}
{%block custom_styles%}
<style>
#card {
position: relative;
width: 320px;
display: block;
margin: 150px auto;
text-align: center;
font-family: 'Source Sans Pro', sans-serif;
}

#upper-side {
padding: 2em;
background-color: #8BC34A;
display: block;
color: #fff;
border-top-right-radius: 8px;
border-top-left-radius: 8px;
}

#checkmark {
font-weight: lighter;
fill: #fff;
margin: -3.5em auto auto 20px;
}

#status {
font-weight: lighter;
text-transform: uppercase;
letter-spacing: 2px;
font-size: 1em;
margin-top: -.2em;
margin-bottom: 0;
}

#lower-side {
padding: 2em 2em 5em 2em;
background: #fff;
display: block;
border-bottom-right-radius: 8px;
border-bottom-left-radius: 8px;
}

#message {
margin-top: -.5em;
color: #757575;
letter-spacing: 1px;
}

#contBtn {
position: relative;
top: 1.5em;
text-decoration: none;
background: #8bc34a;
color: #fff;
margin: auto;
padding: .8em 3em;
-webkit-box-shadow: 0px 15px 30px rgba(50, 50, 50, 0.21);
-moz-box-shadow: 0px 15px 30px rgba(50, 50, 50, 0.21);
box-shadow: 0px 15px 30px rgba(50, 50, 50, 0.21);
border-radius: 25px;
-webkit-transition: all .4s ease;
-moz-transition: all .4s ease;
-o-transition: all .4s ease;
transition: all .4s ease;
}

#contBtn:hover {
-webkit-box-shadow: 0px 15px 30px rgba(50, 50, 50, 0.41);
-moz-box-shadow: 0px 15px 30px rgba(50, 50, 50, 0.41);
box-shadow: 0px 15px 30px rgba(50, 50, 50, 0.41);
-webkit-transition: all .4s ease;
-moz-transition: all .4s ease;
-o-transition: all .4s ease;
transition: all .4s ease;
}

</style>
{%endblock%}
{% block content %}

<section>
    <div class="rt-container">
        <div class="col-rt-12">
            <div class="Scriptcontent">

                <!-- partial:index.partial.html -->
                <div id='card' class="animated fadeIn">
                    <div id='upper-side'>
                        <?xml version="1.0" encoding="utf-8"?>
                        <!-- Generator: Adobe Illustrator 17.1.0, SVG Export Plug-In . SVG Version: 6.00 Build 0)  -->
                        <!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN"
                        "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd">
                        <svg version="1.1" id="checkmark" xmlns="http://www.w3.org/2000/svg"
                             xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" xml:space="preserve">
        <path d="M131.583,92.152l-0.026-0.041c-0.713-1.118-2.197-1.447-3.316-0.734l-31.782,20.257l-4.74-12.65
	c-0.483-1.29-1.882-1.958-3.124-1.493l-0.045,0.017c-1.242,0.465-1.857,1.888-1.374,3.178l5.763,15.382
	c0.131,0.351,0.334,0.65,0.579,0.898c0.028,0.029,0.06,0.052,0.089,0.08c0.08,0.073,0.159,0.147,0.246,0.209
	c0.071,0.051,0.147,0.091,0.222,0.133c0.058,0.033,0.115,0.069,0.175,0.097c0.081,0.037,0.165,0.063,0.249,0.091
	c0.065,0.022,0.128,0.047,0.195,0.063c0.079,0.019,0.159,0.026,0.239,0.037c0.074,0.01,0.147,0.024,0.221,0.027
	c0.097,0.004,0.194-0.006,0.292-0.014c0.055-0.005,0.109-0.003,0.163-0.012c0.323-0.048,0.641-0.16,0.933-0.346l34.305-21.865
	C131.967,94.755,132.296,93.271,131.583,92.152z"/>
                            <circle fill="none" stroke="#ffffff" stroke-width="5" stroke-miterlimit="10" cx="109.486"
                                    cy="104.353" r="32.53"/>
      </svg>
                        <h3 id='status'>
                            Success
                        </h3>
                    </div>
                    <div id='lower-side'>
                        <p id='message'>
                            Congratulations, {{message}}
                        </p>
                        <a href="#" id="contBtn">Continue</a>
                    </div>
                </div>
                <!-- partial -->


            </div>
        </div>
    </div>
</section>
{% endblock %}