car_rent/car_rent/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('captcha/', include('captcha.urls')),
    path('', include('cars.urls', namespace='cars')),
    path('', include('users.urls', namespace='users')),


]
if settings.DEBUG:
    urlpatterns = [
                      # ...
                      path("__debug__/", include("debug_toolbar.urls")),
                  ] + urlpatterns
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

car_rent/cars/urls.py
from django.urls import path
from .views import *
from django.views.decorators.cache import cache_page

app_name = 'cars'
urlpatterns = [
    path('', index, name='home'),
    path('car-posts', CarView.as_view(), name='cars'),
    path('car-details/<slug:car_slug>/', CarDetails.as_view(), name='car_details'),
    path('about/', about, name='about'),
    path('contact/', ContactFormView.as_view(), name='contact'),
    path('map/', MapView.as_view(), name='map'),
    path('add-car/', AddCarView.as_view(), name='add_car'),
    path('success/', successful_post, name='success')

]
# path('', cache_page(80)(HomeView.as_view()), name='home'),
# path('about/', cache_page(80)(about), name='about'),

car_rent/users/urls.py
from django.urls import path
from .views import *
from django.views.decorators.cache import cache_page

app_name = 'users'
urlpatterns = [

    path('register/', SignUp.as_view(), name='register'),
    path('login/', LoginUser.as_view(), name='login'),
    path('logout/', logout_user, name='logout'),
    path('user_profile/<slug:user_slug>/', ShowUser.as_view(), name='user_profile'),
    path('update_profile/', UpdateProfileView.as_view(), name='update_profile'),

]

car_rent/users/models.py
from django.db import models
from django.contrib.auth.models import User
import datetime
from django.urls import reverse



def user_avatar_upload_to(instance, filename):
    # Assuming you have a UserProfile model with a OneToOneField to the User model
    user_slug = instance.slug
    current_time = datetime.datetime.now()
    filename = f'{current_time}_{filename}'
    return f'avatars/{user_slug}/{filename}'


class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    slug = models.SlugField(unique=True, verbose_name='URL', db_index=True, max_length=255)
    first_name = models.CharField(max_length=30)
    last_name = models.CharField(max_length=30)
    bio = models.TextField()
    avatar = models.ImageField(upload_to=user_avatar_upload_to, null=True, blank=True)

    def __str__(self):
        return self.user.username

    def get_absolute_url(self):
        return reverse('users:user_profile', kwargs={'user_slug': self.slug})

car_rent/users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError
from django.utils.text import slugify

from .models import UserProfile


class RegistrationForm(UserCreationForm):
    email = forms.EmailField(max_length=200, help_text='Required')

    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')  # Add other fields as needed

    def clean_username(self):  # custom validator
        username = self.cleaned_data['username']
        if len(username) < 5:
            raise ValidationError('Too short username')
        elif len(username) > 30:
            raise ValidationError('Too long username')
        return username

    def save(self, commit=True):
        user = super(RegistrationForm, self).save(commit=False)
        user.email = self.cleaned_data['email']

        if commit:
            user.save()

            # Create UserProfile
            UserProfile.objects.create(
                user=user,
                first_name='',
                last_name='',
                bio='',
                slug=slugify(self.cleaned_data['username']),
                avatar=''  # You can adjust this field as needed
            )

        return user


class LoginForm(AuthenticationForm):
    username = forms.CharField()
    password = forms.PasswordInput()


class ProfileForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ('first_name', 'last_name', 'bio', 'avatar')


class UpdateProfileForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ('first_name', 'last_name', 'bio', 'avatar')

    def clean_first_name(self):  # custom validator
        first_name = self.cleaned_data['first_name']
        if len(first_name) < 5:
            raise ValidationError('Too short name')
        elif len(first_name) > 30:
            raise ValidationError('Too long name')
        return first_name

car_rent/users/views.py
from django.contrib.auth import logout
from django.http import Http404
from django.contrib.auth.views import LoginView
from django.shortcuts import redirect, render, get_object_or_404
from django.urls import reverse_lazy
from django.views import View
from django.views.generic import CreateView, DetailView
from .forms import RegistrationForm, LoginForm, UpdateProfileForm
from .models import UserProfile
from .utils import DataMixin


class SignUp(DataMixin, CreateView):
    form_class = RegistrationForm
    success_url = reverse_lazy('users:login')
    template_name = 'users/registration.html'

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        title = self.get_user_context(title="Registration")
        return {**context, **title}


class LoginUser(DataMixin, LoginView):
    form_class = LoginForm
    template_name = 'users/login.html'

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        title = self.get_user_context(title="Login")
        return {**context, **title}

    def get_success_url(self):
        return reverse_lazy('cars:home')


class ShowUser(DataMixin, DetailView):
    template_name = 'users/profile.html'
    model = UserProfile
    slug_url_kwarg = 'user_slug'
    context_object_name = 'user_profile'

    def get_object(self, queryset=None):
        user_profile = get_object_or_404(self.model.objects.select_related('user'),
                                         slug=self.kwargs[self.slug_url_kwarg])
        if user_profile.user != self.request.user:
            raise Http404("You do not have permission to view this profile.")
        return user_profile

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)

        title = self.get_user_context(title="Profile")
        return {**context, **title}


class UpdateProfileView(DataMixin, View):
    template_name = 'users/update_profile.html'

    def get(self, request, *args, **kwargs):
        # Fetch user profile using ORM
        profile = UserProfile.objects.get(user=request.user)

        # Populate form with user profile data
        form = UpdateProfileForm(instance=profile)

        return render(request, self.template_name, {'form': form})

    def post(self, request, *args, **kwargs):
        form = UpdateProfileForm(request.POST, request.FILES)

        if form.is_valid():
            # Update user profile using ORM
            profile = UserProfile.objects.get(user=request.user)
            profile.first_name = form.cleaned_data['first_name']
            profile.last_name = form.cleaned_data['last_name']
            profile.bio = form.cleaned_data['bio']
            profile.avatar = form.cleaned_data['avatar']
            profile.save()

            # Redirect to a success page
            return reverse_lazy('cars:success')

        return render(request, self.template_name, {'form': form})

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        title = self.get_user_context(title="Update profile")
        return {**context, **title}


def logout_user(request):
    logout(request)
    return redirect('users:login')

car_rent/users/templates/users/login.html
{% extends 'cars/base.html' %}
{% load static%}

{% block content %}
<div class="container mt-5">
    <div class="row justify-content-center">
        <div class="col-md-6">
            <div class="card">
                <div class="card-header"><b>Login</b></div>
                <div class="card-body">
                    <form method="post">
                        {% csrf_token %}

                        {%for f in form%}
                        <p><label class="form-label" for="{{ f.id_for_label }}">{{f.label}}: </label>{{ f }}</p>
                        {%if f.errors%}
                        <div class="error-block">{{ f.errors }}</div>
                        {%endif%}
                        {%endfor%}
                        {%if form.non_field_errors%}
                        <div class="error-block">{{form.non_field_errors}}</div>
                        {%endif%}
                        <button class="button-80" role="button" type="submit">Log In</button>

                    </form>
                    <p class="mt-3">Do not have an account? <a href="{% url 'users:register' %}">Create an account</a></p>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

car_rent/users/templates/users/profile.html
{% extends 'cars/base.html' %}
{% load static %}

{% block content %}
<div class="container rounded bg-white mt-5 mb-5">
    <div class="row">
        <div class="col-md-3 border-right">
            <div class="d-flex flex-column align-items-center text-center p-3 py-5">
                {%if user_profile.avatar %}

                <img class="rounded-circle mt-5" width="150px" src="{{user_profile.avatar.url}}">
                {%else%}
                <img class="rounded-circle mt-5" width="150px" src="{% static 'users/img/default-avatar.jpg' %}">
                {%endif%}
                <span class="font-weight-bold">{{user_profile.user.username}}</span>
                <span class="text-black-50">{{user_profile.user.email}}</span>
            </div>
        </div>
        <div class="col-md-5 border-right">
            <div class="p-3 py-5">
                <div class="d-flex justify-content-between align-items-center mb-3">
                    <h4 class="text-right">Profile Settings</h4>
                </div>
                <div class="row mt-2">
                    <div class="col-md-6">
                        <label class="labels">First Name</label>
                        {%if user_profile.first_name%}
                        <p>{{user_profile.first_name}}</p>
                        {%else%}
                        <p>Empty</p>
                        {%endif%}
                    </div>
                    <div class="col-md-6">
                        <label class="labels">Last_name</label>
                        {%if user_profile.last_name%}
                        <p>{{user_profile.last_name}}</p>
                        {%else%}
                        <p>Empty</p>
                        {%endif%}
                    </div>


                </div>
                <div class="row mt-3">
                    <div class="col-md-12">
                        <label class="labels">Biography</label>
                        {%if user_profile.bio%}
                        <p>{{user_profile.bio}}</p>
                        {%else%}
                        <p>Empty</p>
                        {%endif%}
                    </div>

                </div>

                <div class="mt-5 text-center">
                    <a class="button-80" href="{% url 'users:update_profile'%}">Alter Profile</a>

                </div>
            </div>
        </div>

    </div>
</div>

{% endblock %}

car_rent/users/templates/users/registration.html
{% extends 'cars/base.html' %}


{% block content %}
<div class="container mt-5">
    <div class="row justify-content-center">
        <div class="col-md-6">
            <div class="card">
                <div class="card-header">Register</div>
                <div class="card-body">
                    <form method="post">
                        {% csrf_token %}
                        {% for f in form %}
                        <p><label class="form-label" for="{{ f.id_for_label }}">{{f.label}}: </label>{{ f }}</p>
                        <div class="form-error">{{ f.errors }}</div>
                        {% endfor %}


                        <button type="submit" class="btn btn-primary">Register</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

car_rent/users/templates/users/update_profile.html
{% extends 'cars/base.html' %}
{%load static%}

{% block content %}
<div class="container mt-5">
    <div class="row justify-content-center">
        <div class="col-md-6">
            <div class="card">
                <div class="card-header"><b>Registration</b></div>
                <div class="card-body">
                    <form method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {% for f in form %}
                        <p><label class="form-label" for="{{ f.id_for_label }}">{{f.label}}: </label>{{ f }}</p>
                        {%if f.errors%}
                        <div class="error-block">{{ f.errors }}</div>
                        {%endif%}
                        {% endfor %}
                        <button type="submit" class="button-80">Save Changes</button>


                    </form>
                    <p class="mt-3">Already have an account? <a href="{% url 'users:login' %}">Login here</a></p>
                </div>
            </div>
        </div>
    </div>
</div>


{% endblock %}